version: "3"
services: 
  database:
    image: mysql:5.6
    volumes : 
      - mysql_storage:/var/lib/mysql
    networks:mynetwork    
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_USER: ved
      MYSQL_PASSWORD: ved
      MYSQL_DATABASE: mydatabase


  nextcloud:         
    image: nextcloud:latest
    restart: always
    networks:mynetwork
    depends_on: 
      - database
    ports:
      - 1234:80
    volumes:
      - nextcloud_storage:/var/www/html

volumes:
  mysql_storage:
  nextcloud_storage:
